title: 🎓 Spencer's Wiki

plugins:
  - jekyll-katex
  - jekyll-default-layout
  - jekyll-relative-links
  - jekyll-readme-index
  - jekyll-titles-from-headings

theme: jekyll-theme-primer
repository: spencerwooo/foam-wiki
